### ISSUE TITLE
Can you implement GPU with the tflite?

### ISSUE THREAD

**Issue by lmy931** [sauvignon1989/PoseEstimationForMobileInJava#2]
I learned a lot from your code.
The tensorflow has released GPU-version tflite, can you enable GPU?

**Comment by bemyae** [comment]
@lmy931 Sorry for not replying sooner. I'm not going to maintain or upgrade this java code anymore except for severe bug. Please check the [original Kotlin implementation](https://github.com/edvardHua/PoseEstimationForMobile/tree/master/android_demo/demo_tflite_gpu)
